### ISSUE TITLE
From won't accept any number

### ISSUE THREAD

**Issue by blahblahyaya** [ipalindromi/pyramid-challenge-workout#1]
No matter what number I type in your demo app (https://ipalindromi.github.io/pyramid-challenge/), I get "You must enter your one rep max" and "fill out the options first" in the output box. Same result on Safari and Chrome.
<img width="798" alt="screen shot 2017-12-01 at 11 51 09 pm" src="https://user-images.githubusercontent.com/1041423/33513192-8baf0738-d6f2-11e7-80f5-988d2d307c20.png">

**Comment by ipalindromi** [comment]
Sure enough, thanks for the heads-up! I will take a look and get a new build out for the demo soon.

**Comment by ipalindromi** [comment]
The demo should now work! Thanks for posting this issue!
